Add mkdocs documentation
Imageomics/pybioclip pull request #66
Opened 2024-11-26 15:33 UTC by johnbradley

Simplifies the README and adds a mkdocs-based documentation website. Pulls changes from the wiki. After this change the wiki will not be used. Adds logic to pull in python API.

To build/view the documentation run:
```
pip install mkdocs mkdocs-material mkdocstrings-python mkdocs-material-extensions
mkdocs serve
```

Fixes #65

2024-11-26 20:05 UTC, egrace479 reviewed
This looks great! A few stylistic suggestions and I think a couple pages are missing.

2024-11-26 20:16 UTC, johnbradley commented on mkdocs.yml
Hah. I forgot to run `git add ...`.

2024-11-26 20:22 UTC, johnbradley commented on mkdocs.yml
I pushed the two files.

2024-11-26 21:02 UTC, egrace479 reviewed
Last two suggestions and I think it's good!

I'd just add a note on the homepage of the wiki that the docs have moved to the site in case anyone's looking there for now.

2024-11-26 21:02 UTC, egrace479 commented on docs/docker.md
> +All examples below require an image file named [Ursus-arctos.jpeg](https://huggingface.co/spaces/imageomics/bioclip-demo/resolve/main/examples/Ursus-arctos.jpeg) in the current directory.
```suggestion
All examples below require an image file named [Ursus-arctos.jpeg](https://huggingface.co/spaces/imageomics/bioclip-demo/blob/main/examples/Ursus-arctos.jpeg) in the current directory.
```
Point to image within the repo instead of just image (like at the beginning of the tutorials).

2024-11-26 21:11 UTC, egrace479 commented
Since this is going to supplant #61, wanted to recall [this change suggestion](https://github.com/Imageomics/pybioclip/pull/61#pullrequestreview-2433458406). It probably requires an updated test too, so a bit out-of-scope here, but it's related and don't want it getting lost.

2024-11-26 22:51 UTC, thompsonmj requested changes
Two inline points.

Also optionally, we could add a link to the PyPI package in the footer of the site by placing:
```
extra:
  social:
    - icon: simple/pypi
      link: https://pypi.org/project/pybioclip/
```
into `mkdocs.yml`.

another option would be for the Docker image with:
```
    - icon: simple/docker
      link: https://github.com/Imageomics/pybioclip/pkgs/container/pybioclip
```
To do the same for the Apptainer image, it would need a custom icon because I couldn't find the Apptainer logo in the default sources.

This only looks any good with 2 or more icons down there in my opinion

2024-11-26 22:51 UTC, thompsonmj commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
```suggestion
Command line tool and python package to simplify the use of [BioCLIP](https://imageomics.github.io/bioclip/).

Key features include:

- **Taxonomic label prediction** for images across ranks in the Linnaean hierarchy (tunable from kingdom to species).
- **Custom label predictions** from user-supplied classification categories.
- **Image embedding generation** in a text-aligned feature space.
- **Batch image processing** with performance optimizations.
- **Workflow integration** for computational pipelines.

It is designed to enable users without requiring in-depth knowledge of machine learning or computer vision.
```

I feel this could be reworded for improved clarity. Also, it may be misleading to state that "no particular understanding of ML" is needed if target users may not know what "semantic embeddings" are without prior knowledge of CLIP. The term 'semantic' is meaningful though ... for the embedding feature bullet, perhaps a footnote with a more in-depth definition? Or does the point as listed hear hint to it well enough?

2024-11-27 14:05 UTC, johnbradley commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
This paragraph is copied from the main README. I don't think users need to know what an embedding is to run the tool. ie.`bioclip predict butterfly.png` or `bioclip embed butterfly.png`. They might not know why they would want to run the tool.

2024-11-27 14:07 UTC, johnbradley commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
I do like adding the list of features. I'm going to commit the suggestion so I can see what it looks like rendered.

2024-11-27 14:14 UTC, johnbradley commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
![Screenshot 2024-11-27 at 9 10 15 AM](https://github.com/user-attachments/assets/2cf7e715-337d-403b-a521-cf5242daaca1)

The Workflow Integration line feels like a bit of a strech. That makes me think we might provide a CWL tool definition or a snakemake rule. I'm going to update this to focus on the container support for use with a workflow.

2024-11-27 14:30 UTC, johnbradley commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
I added links to the command line examples for each key feature and changed the wording for the last item.
<img width="751" alt="Screenshot 2024-11-27 at 9 25 48 AM" src="https://github.com/user-attachments/assets/dbe0ab34-6e54-4768-a623-b7a74b1768a9">

I also added back the line about ease of use. I really want to underscore the idea that you just run a simple command and make use of a ML model.

2024-11-27 14:35 UTC, johnbradley commented
Using `social` for pypi seems incorrect to me. PyPi isn't social media.

2024-11-27 15:59 UTC, egrace479 commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
I think the line 
> It is designed to enable users without requiring in-depth knowledge of machine learning or computer vision.

makes the same point that it doesn't really require the knowledge, while not dismissing any need (or recommendation) for some understanding of what the tool is/does. There's a tendency to use ML tools without understanding what they actually are or do (i.e., limitations and biases). I feel like this softens it to still say ease of use without dismissing that or crossing into a disclaimer, but perhaps there's a mid-ground for it?

Just my two cents; I think the linked key features is a nice addition.

2024-11-27 16:25 UTC, egrace479 commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
Sure. Maybe more like "no specific ML _coding_ knowledge is required"?

2024-11-27 16:41 UTC, johnbradley commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
I updated the text with this last tweak and created #67 to handle the larger concern.

2024-11-27 21:09 UTC, thompsonmj commented on docs/index.md
> +Command line tool and python package to simplify using [BioCLIP](https://imageomics.github.io/bioclip/), including for taxonomic or other label prediction on (and thus annotation or labeling of) imag
This looks great! I feel it's much more appealing to a new visitor in this format.

2024-11-27 21:35 UTC, thompsonmj commented on docs/command-line-api.md
> +# Command Line API
Minor note: Would "Command-Line Help" be a more intuitive heading and page name in the navigation here since this shows the `--help` output rather than specifically how to use the CLI programmatically?

2024-11-27 21:39 UTC, thompsonmj approved these changes
One optional comment, otherwise looks good!

2024-11-28 18:13 UTC, hlapp approved these changes
See inline edits and comments.

2024-11-28 18:13 UTC, hlapp commented on mkdocs.yml
> +  The Imageomics Institute is supported by the National Science Foundation under Award No. 2118240 "HDR Institute: Imageomics: A New Frontier of Biological Information Powered by Knowledge-Guided Mac
This is an acknowledgment statement, not a copyright or license statement. But I suppose this is the only way to place this as a footer or something?

I'd argue that (1) this doesn't have to be a footer on every page, and (2) is perhaps best kept on an acknowledgments page.

2024-12-02 14:41 UTC, johnbradley commented on docs/docker.md
> +In order to access your images the docker container requires you to [mount a volume](https://docs.docker.com/engine/storage/volumes). To avoid redownloading various bioclip files mounting a volume to
The examples below show OS specific ways of mounting in your home directory (eg. `-v $(pwd):/home/bcuser`).

2024-12-02 14:42 UTC, johnbradley commented on docs/docker.md
> +In order to access your images the docker container requires you to [mount a volume](https://docs.docker.com/engine/storage/volumes). To avoid redownloading various bioclip files mounting a volume to
The cache directory could be any directory. For example lab members might share a single directory. Users just need to mount a directory to hold .cache.

2024-12-02 14:46 UTC, johnbradley commented on mkdocs.yml
> +  The Imageomics Institute is supported by the National Science Foundation under Award No. 2118240 "HDR Institute: Imageomics: A New Frontier of Biological Information Powered by Knowledge-Guided Mac
This is the same content from the [imageomics guide footer](https://github.com/Imageomics/Imageomics-guide/blob/6c32748c79ac1e485cf63163642852c000b8e1b8/mkdocs.yaml#L61).
Added here https://github.com/Imageomics/pybioclip/pull/66#discussion_r1859150494.

I'll move this to an Acknowledgments page so we can see how that looks.

2024-12-02 15:13 UTC, johnbradley commented on docs/docker.md
> +In order to access your images the docker container requires you to [mount a volume](https://docs.docker.com/engine/storage/volumes). To avoid redownloading various bioclip files mounting a volume to
I'll create an issue for this so we can proceed with this PR.

2024-12-02 15:24 UTC, merged

2024-12-02 16:05 UTC, hlapp commented on mkdocs.yml
> +  The Imageomics Institute is supported by the National Science Foundation under Award No. 2118240 "HDR Institute: Imageomics: A New Frontier of Biological Information Powered by Knowledge-Guided Mac
Acknowledgment page looks great 👍