Improve performance and prediction results
Imageomics/pybioclip pull request #8
Opened 2024-04-20 18:12 UTC by johnbradley

Introduces two classes that will cache the model so creating predictions for multiple images will only load the model and the tree of life embeddings once.

Changes the prediction returned values to be more consistent. One deviation from what was requested with issue #1 is flattening the results to simplify creating a pandas DataFrame.

Fixes #1

Simplifies the command line interface to default to csv format and process multiple images.

Adds tests that create predictions. These test require downloading the model so may be inappropriate for automated testing. Tests can be run with pytest.

2024-04-22 23:16 UTC, hlapp approved these changes
See inline suggestions. Otherwise 👍

2024-04-23 17:43 UTC, egrace479 requested changes
Looks good, but noticed a couple things that need to be adjusted to match changes and make examples clearer.

2024-04-23 17:43 UTC, egrace479 commented on src/bioclip/__main__.py
>    --output=OUTFILE     save output to a filename instead of printing it [default: stdout]
```suggestion
  --output=OUTFILE     print output to file OUTFILE [default: stdout]
```
Matching change in README.

2024-04-23 17:43 UTC, egrace479 commented on README.md
> +from bioclip import TreeOfLifeClassifier, Rank
```suggestion
import pandas as pd
from bioclip import TreeOfLifeClassifier, Rank
```

2024-04-23 17:43 UTC, egrace479 commented on README.md
>  - `--output OUTPUT` - save output to a filename instead of printing it [default: stdout]
```suggestion
- `--output OUTPUT` - print output to file OUTFILE [default: stdout]
```
Matching change above.

2024-04-23 17:43 UTC, egrace479 commented on README.md
>  #### Optional arguments for predicting from a list of classes:
Update the `--output` parameter description here like above ("print output to file OUTFILE [default: stdout]").

These two may not be needed, though I suppose it's a good point of clarification.

2024-04-23 17:53 UTC, johnbradley commented on README.md
>  #### Optional arguments for predicting from a list of classes:
I removed the output and format flags from this section. Since the usage is displayed earlier I don't see why users would need to see those flags again. I left in the options specific to certain activities
- custom list - `--cls`
- tree of life - `--k` and `--rank`

2024-04-23 20:09 UTC, egrace479 commented on README.md
> +```
Is there a reason for not formatting this example with `python` like the other two in the Python Package examples?

2024-04-23 20:17 UTC, johnbradley commented on README.md
> +```
No.

2024-04-23 20:26 UTC, egrace479 approved these changes
LGTM!

2024-04-23 21:27 UTC, merged